### ISSUE TITLE
Missing space before function parentheses. + VS + {Alt+shift+F}

### ISSUE THREAD

**Issue by noxcionum** [standard/ts-standard#111]
**What version of this package are you using?**
latest

**What operating system, Node.js, and npm version?**
WINServer 2016 npm@6.14.6

**What happened?**
When I use (Alt+shift+F), then i get code without space and ts-standard show me error
![image](https://user-images.githubusercontent.com/3900850/103278138-cf543580-49db-11eb-8942-537c235f0c63.png)

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by Divlo** [comment]
`ts-standard` is not related to VSCode, it is only a npm package but it can be used with `vscode-standardjs` extension.
Maybe you have prettier installed and it auto-formats without the space, we'd like to integrate `prettier` built-in, it is currently a work in progress, you can see our discussions in #102. 
Also there is also a open pull request to implement it in `standard-engine` : https://github.com/standard/standard-engine/issues/230

To fix this issue you could write something like that :
```ts
function updateStatusPDFOK () {
  return StatusPDFOK
}
```
@noxcionum
