### ISSUE TITLE
Unnecessarily quoted property 'Authorization' found. (quote-props) + VS

### ISSUE THREAD

**Issue by noxcionum** [standard/ts-standard#112]
**What version of this package are you using?**
latest

**What operating system, Node.js, and npm version?**
WINServer 2016 npm@6.14.6

**What happened?**
![image](https://user-images.githubusercontent.com/3900850/103284901-991fb180-49ed-11eb-9ef3-24c6a00e1750.png)
How to fix this?

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by Divlo** [comment]
Hey! @noxcionum 
To fix this error, simply unquote 'Authorization'.
so something like this :
```ts
{
  Authorization: accessHeader,
  'Content-Type': 'application/json'
}
```

**Comment by noxcionum** [comment]
Good. This fixed the problem

**Comment by alannaidon** [comment]
Hi! 
I'm having the same issue, but when using `Mongoose` and I can not unquote. WHat could I do?

```
{
      $match: {
        $or: [
          { '$validd': [] },
          { '$validd.createdAt': { $lt: new Date(interval) } },
        ],
      },
    },
```

I can unquote `validd`, but in order to unquote `valid..XXX` I would need to create an interface. Any other work around?

**Comment by aarushikakkar** [comment]
Remove quotes from keys
