### ISSUE TITLE
Parsing error: Unexpected token. Class

### ISSUE THREAD

**Issue by noxcionum** [standard/ts-standard#113]
**What version of this package are you using?**

**What operating system, Node.js, and npm version?**
WINServer 2016 npm@6.14.6

**What happened?**
When i create new class, a have this error
![image](https://user-images.githubusercontent.com/3900850/103479661-55a7b780-4de0-11eb-925d-6da3042af128.png)

and errors highligt is  not work

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by Divlo** [comment]
As I said in #111, "ts-standard is not related to VSCode, it is only a npm package but it can be used with vscode-standardjs extension.", you're not using `ts-standard` engine there, but you're using `standard`. @noxcionum
