### ISSUE TITLE
Moving to the official standard org

### ISSUE THREAD

**Issue by LinusU** [standard/ts-standard#14]
Hey,

Thanks for this wonderful library, made it really easy to get started with `eslint-config-standard-with-typescript`!

Would you be interested in moving this repo to the official Standard repo here on GitHub? No pressure if you don't want to.

If you would like that, you would get added to the Standard team as well. You'll continue to maintain this module, and we'll try and help out as well.

I haven't taken this up with anyone else in the team yet since I just found out about this package, but I cannot imaging that there would be any objections ☺️ 

Cheers 🍻

**Comment by toddbluhm** [comment]
I am actually already a member of the Standard team. I created this separately as it was still in development and I wanted to see what kind of tracking it would get. I am certainly willing to consider the transfer.

**Comment by LinusU** [comment]
Hehe, ah. Yeah might be a good idea to let it live here while we see what kind of traction it gets 👍 

Looking forward to trying it out in our team now and reporting/fixing any bugs ☺️

**Comment by toddbluhm** [comment]
Awesome. I look forward to the feedback. It works great for me locally, but I fully expect some weird edges cases around the paths and especially windows issues. File whatever bugs/issues you find and I will get to them when I can 😄

**Comment by Syy0n** [comment]
I really like this lib. Would be really great, if it could be transferred to the official standard repo and maintained by its community.

**Comment by Divlo** [comment]
This repository need definitely to be on the offical Standard organization.
Also in the official website : [https://standardjs.com/#can-i-use-a-javascript-language-variant-like-flow-or-typescript](https://standardjs.com/#can-i-use-a-javascript-language-variant-like-flow-or-typescript), there is a setup for installing Standard with TypeScript, should I use there installation setup or use that library. If I should use this library, you should update the website doc.

**Comment by Divlo** [comment]
@LinusU  What do you think about that ?

> This repository need definitely to be on the offical Standard organization.
> Also in the official website : https://standardjs.com/#can-i-use-a-javascript-language-variant-like-flow-or-typescript, there is a setup for installing Standard with TypeScript, should I use there installation setup or use that library. If I should use this library, you should update the website doc.

**Comment by toddbluhm** [comment]
@LinusU Think maybe it is time to get his repo moved to the official standard org 🎉  No better way to commemorate the `v10` release than marking it as the official move to the org also.

Not sure what needs to happen on the org side to get this done, but once it is moved, I can proceed to update all the files to reference the new location. Also, how does the transfer on `npm` work?

**Comment by Divlo** [comment]
Maybe someone else of the organization can move the project to the official standard org ?

**Comment by toddbluhm** [comment]
The project has been moved.

**Comment by toddbluhm** [comment]
Once I get npm publishing access, I will migrate the npm package to `standardjs` org and get `v10` published under it.
