### ISSUE TITLE
Usage of ESM imports instead of CommonJS

### ISSUE THREAD

**Issue by Divlo** [standard/ts-standard#171]
We should use ESM imports instead of CommonJS.
See: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

It would offer a smoother transition when `standard-engine` has been migrated completely to ESM, see: https://github.com/standard/standard-engine/issues/251.

**Comment by Divlo** [comment]
Blocked by https://github.com/microsoft/TypeScript/pull/44501 and https://github.com/facebook/jest/issues/9430.

`jest` is the main blocker here.

**Comment by Divlo** [comment]
> I have some experience with getting ESM, TypeScript, and Jest so I'd be happy to take a look at this.

Sure, if you know how to do it, feel free to open a PR. :rocket:

> That being said, I love TypeScript a lot, but I don't think that we have to use it here. In fact, I think that I would prefer that `standard`, `semistandard`, and `ts-standard` had as similar code bases as possible. So I believe that we should use the same setup for all of them, regardless wether that is: plain JS, JS + JSDoc checked with TS, or pure TS.

I agree, `standard`, `standardx`, `semistandard` and `ts-standard` should have a similar codebase.

Somehow, I find out the source code of `ts-standard` over complicated.

The main differences between `ts-standard` and `standard-engine` are the CLI flags.

The flags are plurals, for example: `env` in `standard-engine` and `envs` in `ts-standard`.

And more CLI flags: `--project` and `--report` in `ts-standard`.

---

In my opinion: We should rewrite completely `ts-standard` to make it simple stupid like `standard`, `standardx` and `semistandard`, so it's only 3 plain JS files only.

And if needed we implement the features that `ts-standard` has in `standard-engine`.

Would like to know the opinion of @toddbluhm.

**Comment by jimmywarting** [comment]
any progress?

**Comment by toddbluhm** [comment]
Hey,

Sorry that I have been out for a while...busy with life. I see this project as owned by the standard team. As such if you guys think it would be better to rewrite in vanilla js that is good with me.

The reason for adding --project was to allow setting the location of the project file on the cli because a project file is necessary for a lot of the type checking. This is something unique to typescript that is not unique to the other linters.

If you guys don't think the extra flags are necessary then by all means deprecate them 😄 

Hopefully that adds clarity. I'll be around more if you need help or code reviews.

**Comment by tomaswarynyca** [comment]
Is there any future planning for the project?

**Comment by Divlo** [comment]
> Is there any future planning for the project? @toddbluhm @Divlo

Ideally, we want to update `ts-standard` to use the latest ESLint and `standard-engine` versions but this requires kind of a lot of work as a lot of things changed in `standard-engine` v15 compared to v14.

I don't want/have the time personally, to do the work for this, but I will be happy to review any PR for this.
Basically, we want to have a PR, that simplifies a lot `ts-standard` code base, and as said in this comment: https://github.com/standard/ts-standard/issues/171#issuecomment-921521437, a PR that "rewrite" `ts-standard` to be more like `semistandard`, `standardx` etc.
