### ISSUE TITLE
npm version 10.0.0 is actually different

### ISSUE THREAD

**Issue by vladev** [standard/ts-standard#177]
**What version of this package are you using?**

10.0.0

**What operating system, Node.js, and npm version?**

Manjaro Linux, Node v14.17.4, npm 7.24.1, yarn 1.22.11

**What happened?**

Doing `yarn add -D ts-standard` installs version 10.0.0, but it's actually published long time ago and doesn't correspond to what's in this repo. Current version here is still 10.0.0, but there are changes (eslint-config-standard-with-typescript is upgraded to v21, while on npm it's still v19).

**What did you expect to happen?**

Get the latest version of this package.

**Are you willing to submit a pull request to fix this bug?**

No need or PR, just push a new version to npm.

**Comment by vladev** [comment]
OK, version 11 seems unreleased :(

**Comment by Divlo** [comment]
> OK, version 11 seems unreleased :(
> 
> Version 10 on npm is broken as `no-void` lacks `{ "allowAsStatement": true }` making it impossible to mark when one doesn't care about awaiting a promise.

Yes, there is an open PR for v11.0.0: #166.
