### ISSUE TITLE
Package does not provide `@typescript-eslint/parser`

### ISSUE THREAD

**Issue by tedbyron** [standard/ts-standard#217]
**What version of this package are you using?**
11.0.0

**What operating system, Node.js, and npm version?**
x86_64-apple-darwin21.3.0
node v16.14.0/npm 8.5.0
yarn 3.1.1

**What happened?**
when installing packages with yarn, yarn reports the following:
```
ts-standard@npm:11.0.0 [49082] doesn't provide @typescript-eslint/parser (pb50bc), requested by @typescript-eslint/eslint-plugin
```

**What did you expect to happen?**
`ts-standard` should depend on `@typescript-eslint/parser` because `@typescript-eslint/eslint-plugin` lists it as a peer dependency.

**Are you willing to submit a pull request to fix this bug?**
yes

**Comment by btegs** [comment]
Can you also research this issue if you are updating dependencies? https://github.com/standard/ts-standard/issues/222
