### ISSUE TITLE
Release v12.0.0 (latest changes on `master` branch)

### ISSUE THREAD

**Issue by Divlo** [standard/ts-standard#262]
Release the latest changes available on the `master` branch.
Ref: https://github.com/standard/ts-standard/pull/254

**Comment by LinusU** [comment]
Done ✅ 

I created this tag manually: https://github.com/standard/ts-standard/releases/tag/12.0.0

In the future, I think it's better to not bump the version number in PRs, and instead use the `npm version` command which creates and tags a commit specifically for the bump. That way it's always easy to track a version on npm to a specific git commit ☺️ 

I also think that we should add you to Npm, what's your username there?

**Comment by Divlo** [comment]
@LinusU Okay sounds good to me, we will use the `npm version` command with a PR for the bump. :+1:

My npm username: https://www.npmjs.com/~divlo, would be honored to be added. :smile:

**Comment by LinusU** [comment]
Hmm, npm just tells me "Forbidden" in a red banner when I try to add you 🤔 

Might be that I'm not an owner on the package maybe 🤔
