### ISSUE TITLE
The `--version` flag requires the `--project` flag

### ISSUE THREAD

**Issue by lindluni** [standard/ts-standard#263]
**What version of this package are you using?**

12.0.0

**What operating system, Node.js, and npm version?**

OSX, Node v16.15.0, NPM 8.19.2

**What happened?**

The `--version` flag is requiring the `tsconfig.json` be passed in to provide the version.

**What did you expect to happen?**

The `--version` flag should work by simply running `ts-standard --version` and not require `ts-standard --version --project <path-to-config>`

**Are you willing to submit a pull request to fix this bug?**

Yes, if I can figure it out

**Comment by Divlo** [comment]
Fixed by #264.

>
