### ISSUE TITLE
Release v12.0.2

### ISSUE THREAD

**Issue by lindluni** [standard/ts-standard#276]
Hi @Divlo 

Is it possible to publish a 12.0.2 release to NPM to pick up this change: https://github.com/standard/ts-standard/pull/269

Thank you ❤️

**Comment by Divlo** [comment]
Hey! @lindluni

Thanks for the reminder!
I don't have the rights to publish a new version on `npm`, but I opened a PR so hopefully someone from the team can approve and merge and publish a new version on `npm`.
See: https://github.com/standard/ts-standard/pull/277
